### ISSUE TITLE
Error in testing

### ISSUE THREAD

**Issue by karlinnolabs** [MathieuCliche/Sarcasm_detector#1]
Traceback (most recent call last):
  File "traintest.py", line 101, in <module>
    coeff = vec.inverse_transform(classifier.coef_[0])[0]
  File "/Volumes/ext/Sarcasm/venv/lib/python2.7/site-packages/sklearn/feature_extraction/dict_vectorizer.py", line 256, in inverse_transform
    X = check_array(X, accept_sparse=['csr', 'csc'])
  File "/Volumes/ext/Sarcasm/venv/lib/python2.7/site-packages/sklearn/utils/validation.py", line 441, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[ 0.09904719  0.04722879  0.21515831 ..., -0.08783159  0.          0.        ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by naveenbanda** [comment]
Did anyone solve the above error?
